export const NEW_MESSAGE = "NEW_MESSAGE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const REGISTER_REQUEST = "REGISTER_REQUEST"

export const CONTACTS_REQUEST = "CONTACTS_REQUEST"
export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS"
export const CONTACTS_FAILURE = "CONTACTS_FAILURE"

export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL"
export const CLEAR_ACTIVE_CHANNEL = "CLEAR_ACTIVE_CHANNEL"

export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILURE = "USER_FAILURE"

export const SET_SOCKET = "SET_SOCKET"
export const CLEAR_SOCKET = "CLEAR_SOCKET"
